language: c++
compiler:
  - clang
  - gcc
os: linux
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - clang
      - doxygen
      - graphviz
      - snap
      - libx11-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libgl-dev
      - libglu-dev
install:
  - sudo snap install cmake --classic
  - cmake --version || exit
script:
  - bash Scripts/Linux-Build.sh -b